# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "models", path: "../models"
gem "sinatra"
gem 'sinatra-activerecord'
gem "rake"
gem "sqlite3", "~> 1.4"
